# Generated by Django 5.1.2 on 2024-10-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_fooditem_delete_fooditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='fimage',
            field=models.ImageField(default=0, upload_to='image'),
            preserve_default=False,
        ),
    ]
