# Generated by Django 5.1.2 on 2024-10-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Qty',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
