# Generated by Django 5.1.2 on 2024-10-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_cart_qty_delete_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Qty',
            new_name='qty',
        ),
    ]
